### ISSUE TITLE
bug(customrpc): Time left for song not accurate

### ISSUE THREAD

**Issue by SteveeTheCreeper** [nexpid/DettaPlugins#45]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

stevethecreeper

### Detailed Info

When using the {spotify.track.end} the time left isnt always correct
for an example if the song is 2 mins long the RPC displays it's 1:40 or even only 1 minute long and stays at 0:00 till the new song plays

### Steps to Reproduce

Just put the end time variable then select Spotify track end

### Bug Screenshot

don't ask why I have the Spotify songs as a game
![Screenshot_20231024_151725](https://github.com/nexpid/VendettaPlugins/assets/119169182/85f23125-e772-4a30-8c4e-fce6e8c3f5dd)

### System Info

Device: samsung SM-A336E
Model: SM-A336E
Manufacturer: samsung
Brand: samsung

OS: Android
Version: 13

Discord Branch: googleRelease
Discord Version: 199.15
Discord Build: 199015
Vendetta Version: 289ffa4

React Version: 18.2.0
Hermes Bytecode: 94

**Comment by nexpid** [comment]
still have no idea how to fix this tbh

**Comment by nexpid** [comment]
this seems to be a Discord issue, no clueeee how to fix this
