### ISSUE TITLE
How do I use it ?

### ISSUE THREAD

**Issue by Dark-Devil09** [nexpid/DettaPlugins#82]
I can just see manage my hiden servers(I don't have any tho). However I can't understand how do I hide servers using it.

**Comment by Dark-Devil09** [comment]
I mean I can see that hide ball option but clicking on that does nothing

**Comment by SparrowOchon** [comment]
The HideServer plugin does not work. It would probably make more sense to turn this issue into a bug report with a default template you must fill out rather than create a new one.

**Comment by SparrowOchon** [comment]
#92 Is the associated wip fix issue. Thanks @nexpid
